export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import connectDB from '@/lib/mongodb'
import { Project, ProjectRenewal } from '@/models'
import { calcPeriodEnd } from '@/lib/ventures'
import { requirePerm } from '@/lib/rbac'
import { isValidObjectId } from '@/lib/objectId'

// POST /api/projects/[id]/renew
// Marks current MONTHLY project RENEWED + creates a new project for the next period
export async function POST(request, { params }) {
  try {
    const session = await getServerSession(authOptions)
    const denied  = requirePerm(session, 'projects.update')
    if (denied) return denied
    if (!isValidObjectId(params.id)) return NextResponse.json({ error: 'Project not found' }, { status: 404 })

    await connectDB()

    // Atomically claim the project: only one request can flip it to RENEWED, so a
    // double-click / concurrent renew cannot clone the next period twice.
    // Returns the pre-update document.
    const old = await Project.findOneAndUpdate(
      { _id: params.id, projectType: 'MONTHLY', status: { $nin: ['RENEWED', 'CANCELLED'] } },
      { $set: { status: 'RENEWED', renewalStatus: 'RENEWED' } },
      { new: false }
    ).lean()

    if (!old) {
      const cur = await Project.findById(params.id).select('projectType status').lean()
      if (!cur)                          return NextResponse.json({ error: 'Project not found' }, { status: 404 })
      if (cur.projectType !== 'MONTHLY') return NextResponse.json({ error: 'Only MONTHLY projects can be renewed' }, { status: 422 })
      if (cur.status === 'CANCELLED')    return NextResponse.json({ error: 'Cancelled projects cannot be renewed' }, { status: 422 })
      return NextResponse.json({ error: 'Project already renewed' }, { status: 409 })
    }

    // New period starts the day after old period ends (or today if no period)
    const newPeriodStart = old.currentPeriodEnd
      ? new Date(new Date(old.currentPeriodEnd).getTime() + 86400000)
      : new Date()
    // Anchor on the stored billing day so month-end clients don't drift to the 28th.
    const newPeriodEnd = calcPeriodEnd(newPeriodStart, old.billingDay)

    // Clone — strip identity/accounting fields so they reset cleanly
    const {
      _id, __v, projectCode, createdAt, updatedAt,
      paidAmount, approvedExpenses, cancelledAt, cancelReason,
      renewalStatus, status, discount,
      ...rest
    } = old

    // Legacy `discount` (dropped from the schema): until
    // scripts/migrate-drop-project-discount.js has run, `budget` may still be
    // the gross value. Fold the discount in so the next period keeps the net
    // value instead of silently losing the discount.
    const legacyDiscount = Number(discount) || 0
    if (legacyDiscount > 0) {
      rest.budget = Math.max(0, Math.round(((Number(rest.budget) || 0) - legacyDiscount) * 100) / 100)
    }

    let newProject
    try {
      newProject = await new Project({
        ...rest,
        status:             'ACTIVE',   // monthly lifecycle status (lib/ventures MONTHLY_STATUSES)
        renewalStatus:      'ACTIVE',
        currentPeriodStart: newPeriodStart,
        currentPeriodEnd:   newPeriodEnd,
        nextBillingDate:    newPeriodEnd,
        startDate:          newPeriodStart,
        deadline:           null,
        paidAmount:         0,
        approvedExpenses:   0,
        orderDate:          new Date(),
        // projectCode auto-generated by pre-save hook
      }).save()
    } catch (err) {
      // Release the claim so the renewal can be retried.
      await Project.updateOne(
        { _id: old._id, status: 'RENEWED' },
        { $set: { status: old.status, renewalStatus: old.renewalStatus ?? null } }
      )
      throw err
    }

    // Log renewal record linked to NEW project
    await new ProjectRenewal({
      projectId:       newProject._id,
      periodStart:     newPeriodStart,
      periodEnd:       newPeriodEnd,
      billingAmount:   rest.budget ?? 0,
      status:          'PENDING',
      renewedBy:       session.user.id,
    }).save()

    return NextResponse.json({ success: true, newProject: newProject.toJSON() }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/projects/:id/renew]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
