export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import connectDB from '@/lib/mongodb'
import { Project, ProjectRenewal } from '@/models'
import { calcPeriodEnd } from '@/lib/ventures'

// POST /api/projects/[id]/renew
// Marks current MONTHLY project RENEWED + creates a new project for the next period
export async function POST(request, { params }) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
    if (!['SUPER_ADMIN', 'MANAGER'].includes(session.user.role))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    await connectDB()

    const old = await Project.findById(params.id).lean()
    if (!old)                             return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    if (old.projectType !== 'MONTHLY')    return NextResponse.json({ error: 'Only MONTHLY projects can be renewed' }, { status: 422 })
    if (old.status === 'RENEWED')         return NextResponse.json({ error: 'Project already renewed' }, { status: 409 })

    // Mark old project as RENEWED
    await Project.findByIdAndUpdate(params.id, { status: 'RENEWED', renewalStatus: 'RENEWED' })

    // New period starts the day after old period ends (or today if no period)
    const newPeriodStart = old.currentPeriodEnd
      ? new Date(new Date(old.currentPeriodEnd).getTime() + 86400000)
      : new Date()
    const newPeriodEnd = calcPeriodEnd(newPeriodStart)

    // Clone — strip identity/accounting fields so they reset cleanly
    const {
      _id, __v, projectCode, createdAt, updatedAt,
      paidAmount, approvedExpenses, cancelledAt, cancelReason,
      renewalStatus, status,
      ...rest
    } = old

    const newProject = await new Project({
      ...rest,
      status:             'IN_PROGRESS',
      renewalStatus:      'ACTIVE',
      currentPeriodStart: newPeriodStart,
      currentPeriodEnd:   newPeriodEnd,
      nextBillingDate:    newPeriodEnd,
      startDate:          newPeriodStart,
      deadline:           null,
      paidAmount:         0,
      approvedExpenses:   0,
      orderDate:          new Date(),
      // projectCode auto-generated by pre-save hook
    }).save()

    // Log renewal record linked to NEW project
    await new ProjectRenewal({
      projectId:       newProject._id,
      periodStart:     newPeriodStart,
      periodEnd:       newPeriodEnd,
      billingAmount:   old.budget ?? 0,
      discountApplied: old.discount ?? 0,
      status:          'PENDING',
      renewedBy:       session.user.id,
    }).save()

    return NextResponse.json({ success: true, newProject: newProject.toJSON() }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/projects/:id/renew]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
