export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import connectDB from '@/lib/mongodb'
import { Transaction, Invoice } from '@/models'
import { canAccess } from '@/lib/permissions'
import { logActivity } from '@/lib/logActivity'
import { isValidCurrency, BASE_CURRENCY } from '@/lib/currencies'
import { z } from 'zod'

const transactionSchema = z.object({
  type:           z.enum(['INCOME', 'EXPENSE']),
  category:       z.string().min(1),
  amount:         z.coerce.number().positive(),
  description:    z.string().min(1),
  date:           z.string(),
  reference:      z.string().optional().nullable(),
  projectId:        z.string().optional().nullable(),
  invoiceId:        z.string().optional().nullable(),
  clientId:         z.string().optional().nullable(),
  vendorId:         z.string().optional().nullable(),
  freelancerId:     z.string().optional().nullable(),
  agencyId:         z.string().optional().nullable(),
  paidToEmployeeId: z.string().optional().nullable(),
  paidToName:       z.string().optional().nullable(),
  // Multi-currency: amount is in `currency`; for non-BDT, amountBDT is the
  // manually-entered BDT-equivalent actually spent/received. All metrics roll up in BDT.
  currency:       z.string().default(BASE_CURRENCY).refine(isValidCurrency, 'Unsupported currency'),
  amountBDT:      z.coerce.number().positive().optional().nullable(),
  vendor:         z.string().optional().nullable(),
  paidBy:         z.string().optional().nullable(),
  accountManager: z.string().optional().nullable(),
  paymentMethod:   z.string().optional().nullable(),
  expenseCategory: z.string().optional().nullable(),
  receiptUrl:      z.string().optional().nullable(),
  // txnId provided manually only when no receipt; otherwise auto-generated by pre-save hook
  txnId:          z.string().optional().nullable(),
}).superRefine((d, ctx) => {
  if (d.currency !== BASE_CURRENCY && !d.amountBDT) {
    ctx.addIssue({ path: ['amountBDT'], code: 'custom', message: 'Enter the BDT-equivalent for a non-BDT transaction' })
  }
})

// GET /api/transactions
export async function GET(request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
    if (!canAccess(session, 'accounts', 'view'))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    await connectDB()

    const { searchParams } = new URL(request.url)
    const page      = parseInt(searchParams.get('page')  ?? '1',  10)
    const limit     = parseInt(searchParams.get('limit') ?? '50', 10)
    const type      = searchParams.get('type')
    const category  = searchParams.get('category')
    const subcategory = searchParams.get('subcategory')
    const startDate = searchParams.get('startDate')
    const endDate   = searchParams.get('endDate')
    const skip      = (page - 1) * limit

    // category & subcategory are plain fields — match by direct equality.
    // (subcategory is stored in the `expenseCategory` field for both income & expense.)
    const filter = {}
    if (type)        filter.type            = type
    if (category)    filter.category        = category
    if (subcategory) filter.expenseCategory = subcategory
    if (startDate || endDate) {
      filter.date = {}
      if (startDate) filter.date.$gte = new Date(startDate)
      if (endDate)   filter.date.$lte = new Date(new Date(endDate).setHours(23, 59, 59, 999))
    }

    const sort = { date: -1, createdAt: -1 }

    const [transactions, total] = await Promise.all([
      Transaction.find(filter).skip(skip).limit(limit).sort(sort)
        .populate('paidBy',         'name avatar')
        .populate('accountManager', 'name avatar')
        .populate('createdBy',      'name')
        .populate('projectId',      'name projectCode venture'),
      Transaction.countDocuments(filter),
    ])

    return NextResponse.json({
      data: transactions.map(t => t.toJSON()),
      meta: { page, limit, total, pages: Math.ceil(total / limit) },
    })
  } catch (err) {
    console.error('[GET /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// POST /api/transactions
export async function POST(request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
    if (!canAccess(session, 'accounts', 'addTransaction'))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    await connectDB()

    const body   = await request.json()
    const parsed = transactionSchema.safeParse(body)
    if (!parsed.success)
      return NextResponse.json({ error: 'Validation failed', details: parsed.error.flatten() }, { status: 422 })

    const { date, ...rest } = parsed.data

    // txnId, receipt, reference, project etc. are all optional —
    // the pre-save hook auto-generates a txnId when none is provided.

    // Strip empty strings to null
    const clean = Object.fromEntries(
      Object.entries(rest).map(([k, v]) => [k, v === '' ? null : v])
    )

    // BDT-equivalent: for BDT the amounts are identical; for foreign currency use
    // the manually-entered value (validated above).
    const amountBDT = clean.currency === BASE_CURRENCY ? clean.amount : clean.amountBDT

    const transaction = await new Transaction({
      ...clean,
      amountBDT,
      date:      new Date(date),
      createdBy: session.user.id,
    }).save()

    // Sync invoice paidAmount/status when an income transaction is linked to an invoice
    if (clean.type === 'INCOME' && clean.invoiceId) {
      const invoice = await Invoice.findById(clean.invoiceId)
      if (invoice && !['PAID', 'CANCELLED'].includes(invoice.status)) {
        const newPaid = Math.min((invoice.paidAmount ?? 0) + clean.amount, invoice.total)
        invoice.paidAmount = newPaid
        const balance = invoice.total - newPaid
        if (balance <= 0.01) {
          invoice.status = 'PAID'
          if (!invoice.paidAt) invoice.paidAt = new Date(clean.date)
        } else {
          invoice.status = 'PARTIALLY_PAID'
        }
        await invoice.save()
      }
    }

    await transaction.populate([
      { path: 'paidBy',         select: 'name avatar' },
      { path: 'accountManager', select: 'name avatar' },
      { path: 'createdBy',      select: 'name' },
      { path: 'projectId',      select: 'name projectCode venture' },
    ])

    logActivity({
      userId:   session.user.id,
      userRole: session.user.role,
      action:   'CREATE',
      entity:   'TRANSACTION',
      entityId: transaction._id.toString(),
      changes:  JSON.stringify({ type: clean.type, amount: clean.amount, category: clean.category }),
      request,
    })

    return NextResponse.json({ data: transaction.toJSON() }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
