export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import connectDB from '@/lib/mongodb'
import { Transaction, Invoice, Project } from '@/models'
import { requirePerm } from '@/lib/rbac'
import { logActivity } from '@/lib/logActivity'
import { isValidCurrency, BASE_CURRENCY } from '@/lib/currencies'
import { isValidObjectId } from '@/lib/objectId'
import { parseDhakaDay } from '@/lib/dhakaTime'
import { z } from 'zod'

const transactionSchema = z.object({
  type:           z.enum(['INCOME', 'EXPENSE']),
  category:       z.string().min(1),
  amount:         z.coerce.number().positive(),
  description:    z.string().min(1),
  date:           z.string(),
  reference:      z.string().optional().nullable(),
  projectId:        z.string().optional().nullable(),
  invoiceId:        z.string().optional().nullable(),
  clientId:         z.string().optional().nullable(),
  vendorId:         z.string().optional().nullable(),
  freelancerId:     z.string().optional().nullable(),
  agencyId:         z.string().optional().nullable(),
  paidToEmployeeId: z.string().optional().nullable(),
  paidToName:       z.string().optional().nullable(),
  // Multi-currency: amount is in `currency`; for non-BDT, amountBDT is the
  // manually-entered BDT-equivalent actually spent/received. All metrics roll up in BDT.
  currency:       z.string().default(BASE_CURRENCY).refine(isValidCurrency, 'Unsupported currency'),
  amountBDT:      z.coerce.number().positive().optional().nullable(),
  vendor:         z.string().optional().nullable(),
  paidBy:         z.string().optional().nullable(),
  accountManager: z.string().optional().nullable(),
  paymentMethod:   z.string().optional().nullable(),
  expenseCategory: z.string().optional().nullable(),
  receiptUrl:      z.string().optional().nullable(),
  // txnId provided manually only when no receipt; otherwise auto-generated by pre-save hook
  txnId:          z.string().optional().nullable(),
}).superRefine((d, ctx) => {
  if (d.currency !== BASE_CURRENCY && !d.amountBDT) {
    ctx.addIssue({ path: ['amountBDT'], code: 'custom', message: 'Enter the BDT-equivalent for a non-BDT transaction' })
  }
})

// GET /api/transactions
export async function GET(request) {
  try {
    const session = await getServerSession(authOptions)
    const denied  = requirePerm(session, 'finance.transactions.view')
    if (denied) return denied
    await connectDB()

    const { searchParams } = new URL(request.url)
    const page      = parseInt(searchParams.get('page')  ?? '1',  10)
    const limit     = parseInt(searchParams.get('limit') ?? '50', 10)
    const type      = searchParams.get('type')
    const category  = searchParams.get('category')
    const subcategory = searchParams.get('subcategory')
    const startDate = searchParams.get('startDate')
    const endDate   = searchParams.get('endDate')
    const skip      = (page - 1) * limit

    // category & subcategory are plain fields — match by direct equality.
    // (subcategory is stored in the `expenseCategory` field for both income & expense.)
    const filter = {}
    if (type)        filter.type            = type
    if (category)    filter.category        = category
    if (subcategory) filter.expenseCategory = subcategory
    // Date-only filters are Asia/Dhaka calendar days; the end day is inclusive.
    if (startDate || endDate) {
      filter.date = {}
      if (startDate) filter.date.$gte = parseDhakaDay(startDate)?.start ?? new Date(startDate)
      if (endDate) {
        const end = parseDhakaDay(endDate)
        if (end) filter.date.$lt  = end.next
        else     filter.date.$lte = new Date(endDate)
      }
    }

    const sort = { date: -1, createdAt: -1 }

    const [transactions, total] = await Promise.all([
      Transaction.find(filter).skip(skip).limit(limit).sort(sort)
        .populate('paidBy',         'name avatar')
        .populate('accountManager', 'name avatar')
        .populate('createdBy',      'name')
        .populate('projectId',      'name projectCode venture'),
      Transaction.countDocuments(filter),
    ])

    return NextResponse.json({
      data: transactions.map(t => t.toJSON()),
      meta: { page, limit, total, pages: Math.ceil(total / limit) },
    })
  } catch (err) {
    console.error('[GET /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// POST /api/transactions
export async function POST(request) {
  try {
    const session = await getServerSession(authOptions)
    const denied  = requirePerm(session, 'finance.transactions.create')
    if (denied) return denied
    await connectDB()

    const body   = await request.json()
    const parsed = transactionSchema.safeParse(body)
    if (!parsed.success)
      return NextResponse.json({ error: 'Validation failed', details: parsed.error.flatten() }, { status: 422 })

    const { date, ...rest } = parsed.data

    // Expenses are never written to the ledger directly — they must go through
    // the expense-request pipeline (/api/expenses → Paid → Authorized), which
    // creates the EXPENSE transaction when the expense is paid.
    if (rest.type === 'EXPENSE')
      return NextResponse.json({ error: 'Expenses cannot be added directly. Submit an expense request instead.' }, { status: 422 })

    const txDate = new Date(date)
    if (Number.isNaN(txDate.getTime()))
      return NextResponse.json({ error: 'Invalid date' }, { status: 422 })

    // txnId, receipt, reference, project etc. are all optional —
    // the pre-save hook auto-generates a txnId when none is provided.

    // Strip empty strings to null
    const clean = Object.fromEntries(
      Object.entries(rest).map(([k, v]) => [k, v === '' ? null : v])
    )

    // BDT-equivalent: for BDT the amounts are identical; for foreign currency use
    // the manually-entered value (validated above).
    const amountBDT = clean.currency === BASE_CURRENCY ? clean.amount : clean.amountBDT

    // Amount of this transaction expressed in `targetCurrency`, or null when it
    // cannot be converted (foreign → a different foreign currency).
    const amountIn = (targetCurrency) => {
      const cur = targetCurrency || BASE_CURRENCY
      if (cur === clean.currency) return clean.amount
      if (cur === BASE_CURRENCY)  return amountBDT
      return null
    }

    // Validate the invoice link BEFORE writing the ledger row, so a bad link can
    // never leave an orphan income entry behind.
    let invoice = null, invoiceCredit = null
    if (clean.invoiceId) {
      if (!isValidObjectId(clean.invoiceId))
        return NextResponse.json({ error: 'Invalid invoiceId' }, { status: 400 })
      invoice = await Invoice.findById(clean.invoiceId)
      if (!invoice) return NextResponse.json({ error: 'Invoice not found' }, { status: 404 })
      if (!['PAID', 'CANCELLED'].includes(invoice.status)) {
        invoiceCredit = amountIn(invoice.currency)
        if (invoiceCredit == null)
          return NextResponse.json({
            error: `This invoice is in ${invoice.currency}. Record the payment in ${invoice.currency} or ${BASE_CURRENCY} to link it.`,
          }, { status: 422 })
      }
    }

    const transaction = await new Transaction({
      ...clean,
      amountBDT,
      date:      txDate,
      createdBy: session.user.id,
    }).save()

    // Sync invoice paidAmount/status when an income transaction is linked to an
    // invoice (credited in the invoice's own currency).
    if (invoice && invoiceCredit != null) {
      try {
        const total   = Number(invoice.total) || 0
        const newPaid = Math.min((Number(invoice.paidAmount) || 0) + invoiceCredit, total)
        invoice.paidAmount = newPaid
        const balance = total - newPaid
        if (balance <= 0.01) {
          invoice.status = 'PAID'
          if (!invoice.paidAt) invoice.paidAt = txDate
        } else {
          invoice.status = 'PARTIALLY_PAID'
        }
        await invoice.save()
      } catch (err) {
        // Undo the ledger row so a retry cannot double-count the income.
        await Transaction.deleteOne({ _id: transaction._id }).catch(() => {})
        throw err
      }

      // Credit the project too, as the other payment paths do, so its
      // paidAmount / dueAmount / profit agree with its invoices.
      const projectId = invoice.projectId ?? clean.projectId
      if (projectId && isValidObjectId(projectId)) {
        const project = await Project.findById(projectId)
        const projectCredit = project ? amountIn(project.currency) : null
        if (project && projectCredit != null) {
          project.paidAmount = (Number(project.paidAmount) || 0) + projectCredit
          await project.save()
        }
      }
    }

    await transaction.populate([
      { path: 'paidBy',         select: 'name avatar' },
      { path: 'accountManager', select: 'name avatar' },
      { path: 'createdBy',      select: 'name' },
      { path: 'projectId',      select: 'name projectCode venture' },
    ])

    logActivity({
      userId:   session.user.id,
      userRole: session.user.role,
      action:   'CREATE',
      entity:   'TRANSACTION',
      entityId: transaction._id.toString(),
      changes:  JSON.stringify({ type: clean.type, amount: clean.amount, category: clean.category }),
      request,
    })

    return NextResponse.json({ data: transaction.toJSON() }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
