export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import connectDB from '@/lib/mongodb'
import { Transaction } from '@/models'
import { z } from 'zod'

const transactionSchema = z.object({
  type:           z.enum(['INCOME', 'EXPENSE']),
  category:       z.string().min(1),
  amount:         z.coerce.number().positive(),
  description:    z.string().min(1),
  date:           z.string(),
  reference:      z.string().optional().nullable(),
  projectId:      z.string().optional().nullable(),
  clientId:       z.string().optional().nullable(),
  vendorId:       z.string().optional().nullable(),
  freelancerId:   z.string().optional().nullable(),
  currency:       z.string().default('BDT').transform(() => 'BDT'),  // always BDT
  vendor:         z.string().optional().nullable(),
  paidBy:         z.string().optional().nullable(),
  accountManager: z.string().optional().nullable(),
  paymentMethod:  z.enum(['CASH','BANK_TRANSFER','CARD','CHEQUE','ONLINE','OTHER']).optional().nullable(),
  receiptUrl:     z.string().optional().nullable(),
  // txnId provided manually only when no receipt; otherwise auto-generated by pre-save hook
  txnId:          z.string().optional().nullable(),
})

// GET /api/transactions
export async function GET(request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
    if (!['SUPER_ADMIN','MANAGER'].includes(session.user.role))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    await connectDB()

    const { searchParams } = new URL(request.url)
    const page      = parseInt(searchParams.get('page')  ?? '1',  10)
    const limit     = parseInt(searchParams.get('limit') ?? '50', 10)
    const type      = searchParams.get('type')
    const category  = searchParams.get('category')
    const startDate = searchParams.get('startDate')
    const endDate   = searchParams.get('endDate')
    const skip      = (page - 1) * limit

    const filter = {}
    if (type)     filter.type     = type
    if (category) filter.category = category
    if (startDate || endDate) {
      filter.date = {}
      if (startDate) filter.date.$gte = new Date(startDate)
      if (endDate)   filter.date.$lte = new Date(new Date(endDate).setHours(23, 59, 59, 999))
    }

    const [transactions, total] = await Promise.all([
      Transaction.find(filter)
        .skip(skip).limit(limit).sort({ date: -1, createdAt: -1 })
        .populate('paidBy',         'name avatar')
        .populate('accountManager', 'name avatar')
        .populate('createdBy',      'name')
        .populate('projectId',      'name projectCode venture'),
      Transaction.countDocuments(filter),
    ])

    return NextResponse.json({
      data: transactions.map(t => t.toJSON()),
      meta: { page, limit, total, pages: Math.ceil(total / limit) },
    })
  } catch (err) {
    console.error('[GET /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// POST /api/transactions
export async function POST(request) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
    if (!['SUPER_ADMIN','MANAGER'].includes(session.user.role))
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    await connectDB()

    const body   = await request.json()
    const parsed = transactionSchema.safeParse(body)
    if (!parsed.success)
      return NextResponse.json({ error: 'Validation failed', details: parsed.error.flatten() }, { status: 422 })

    const { date, ...rest } = parsed.data

    // txnId required if no receipt
    if (!rest.receiptUrl && !rest.txnId) {
      return NextResponse.json({
        error: 'Transaction ID is required when no receipt is attached',
      }, { status: 422 })
    }

    // Strip empty strings to null
    const clean = Object.fromEntries(
      Object.entries(rest).map(([k, v]) => [k, v === '' ? null : v])
    )

    const transaction = await new Transaction({
      ...clean,
      date:      new Date(date),
      createdBy: session.user.id,
    }).save()

    await transaction.populate([
      { path: 'paidBy',         select: 'name avatar' },
      { path: 'accountManager', select: 'name avatar' },
      { path: 'createdBy',      select: 'name' },
      { path: 'projectId',      select: 'name projectCode venture' },
    ])

    return NextResponse.json({ data: transaction.toJSON() }, { status: 201 })
  } catch (err) {
    console.error('[POST /api/transactions]', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
