// Central model registry — import from here to ensure all models are registered
// before any populate() calls that reference other models.

export { default as User }              from './User.js'
export { default as Employee }          from './Employee.js'
export { default as Client }            from './Client.js'
export { default as Freelancer }        from './Freelancer.js'
export { default as Vendor }            from './Vendor.js'
export { default as Lead, LeadActivity } from './Lead.js'
export { default as Project }           from './Project.js'
export { default as ProjectVendor }     from './ProjectVendor.js'
export { default as ProjectExpense }    from './ProjectExpense.js'
export { default as ProjectRenewal }    from './ProjectRenewal.js'
export { default as ProjectPayment }   from './ProjectPayment.js'
export { default as Task }              from './Task.js'
export { default as Milestone }         from './Milestone.js'
export { default as Timesheet }         from './Timesheet.js'
export { default as Invoice, InvoiceItem } from './Invoice.js'
export { default as Payment }           from './Payment.js'
export { default as Transaction }       from './Transaction.js'
export { default as VendorPayment }     from './VendorPayment.js'
export { default as WithdrawalRequest }      from './WithdrawalRequest.js'
export { default as FreelancerAssignment }   from './FreelancerAssignment.js'
export { default as Earning }           from './Earning.js'
export { default as Agreement }         from './Agreement.js'
export { default as Document }          from './Document.js'
export { default as Attachment }        from './Attachment.js'
export { default as Comment }           from './Comment.js'
export { default as Message }           from './Message.js'
export { default as Notification }      from './Notification.js'
export { default as Attendance }        from './Attendance.js'
export { default as Leave }             from './Leave.js'
export { default as AuditLog }          from './AuditLog.js'
export { default as Setting }           from './Setting.js'
export { default as EditRequest }       from './EditRequest.js'
export { default as CustomRole }            from './CustomRole.js'
export { default as EmployeeOnboarding }    from './EmployeeOnboarding.js'
export { default as PricingCategory }       from './PricingCategory.js'
